DROP TABLE IF EXISTS user_tb;
CREATE TABLE user_tb (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password TEXT NOT NULL,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(20) NOT NULL
);

DROP TABLE IF EXISTS category_tb;
CREATE TABLE category_tb (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    category_name VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS book_tb;
CREATE TABLE book_tb (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    category_id BIGINT NOT NULL,
    publisher VARCHAR(50),
    author VARCHAR(50) NOT NULL,
    register_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    book_name VARCHAR(50) NOT NULL,
    unit_price INT NOT NULL,
    discount_rate INT NOT NULL DEFAULT 0
);

DROP TABLE IF EXISTS order_tb;
CREATE TABLE order_tb (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    order_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    total_price INT NOT NULL,
    status VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS order_item_tb;
CREATE TABLE order_item_tb (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    order_id BIGINT NOT NULL,
    book_id BIGINT NOT NULL,
    `count` INT NOT NULL,
    price INT NOT NULL
);

DROP TABLE IF EXISTS review_tb;
CREATE TABLE review_tb (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    book_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL UNIQUE,
    score INT NOT NULL,
    content TEXT
);